<?php

namespace WCS\CoavBundle\Repository;

/**
 * ResevationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResevationRepository extends \Doctrine\ORM\EntityRepository
{
}
